### ISSUE TITLE
[Feature] In-game report system

### ISSUE THREAD

**Issue by NicoNekoDev** [NicoNekoDev/AstralBooks#11]
Report system so players can report bugs/errors in-game without going on a forum for this or spam this.
- Maybe rewards for confirmed bugs?

**Comment by PikaMug** [comment]
This is a cool idea, but there's reasons other plugins don't do this:

- Fees for issue tracking site APIs or hosting your own
  - User complaints if hosted site ever goes offline
- Junk reports from command spam and/or bots
- Difficult to reach user without email/SMS notification
- Tougher onboarding compared to well-known sites

You do you, but it might be best to focus your efforts elsewhere.

**Comment by NicoNekoDev** [comment]
It was an idea for an in-game report system for players to use. 😂
Other plugins do GUIs, while I do books! 🙃
