### ISSUE TITLE
New version spam

### ISSUE THREAD

**Issue by TomLewis** [NicoNekoDev/AstralBooks#12]
so much spam, one message is enough.
![2018-09-09_15 43 07](https://user-images.githubusercontent.com/144046/45265699-42ba8d80-b447-11e8-8181-d56abf6a1d04.png)

**Comment by NicoNekoDev** [comment]
Can you tell me more about this issue? Like which version of the plugin and server you use, a plugin list, etc.?

**Comment by TomLewis** [comment]
V 2.4.2
Paper Version 1556

**Comment by NicoNekoDev** [comment]
I don't see anything wrong with v2.4.2. If some plugin(s) trigger PlayerJoinEvent multiple times, I can't do anything.

**Comment by TomLewis** [comment]
No other plugins do this, as you can see multiple other plugins also say they have an update without issue.

**Comment by NicoNekoDev** [comment]
Ok I found the bug, I'm gonna fix it today. Sorry for the inconvenience. :)
