### ISSUE TITLE
[Bug] Not working 1.13.1

### ISSUE THREAD

**Issue by CaptainAmpersand** [NicoNekoDev/AstralBooks#13]
### Information
Server version: CraftBukkit version git-Spigot-68acb93-65bb2d0 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT) (Latest release 9/23/2018)
CitizensBooks version 2.4.3
Citizens version 2.0.24-SNAPSHOT (build 1570)

Full output of `/npcbook about`:
/npcbook about doesn't display anything. I literally can't answer this.

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/CaptainAmpersand/000e92854bfc2e00af99a2f71a5f3836
Look at line 1622, it spams a fair amount
CitizensBooks config (upload `plugins/CitizensBooks/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/CaptainAmpersand/5b3be9bd48733df61ff10405f35f5969
Default config.yml
### Details

Describe your issue here.
The plugin 100% will no longer work. /npcbook will not display any kind of notification. To try and diagnose it, I had downgraded CitizensBooks to 2.4.3 (As seen in the logs). That was my third time trying to get it to work. I even deleted my old configs, nothing works.

**Comment by NicoNekoDev** [comment]
Yeah, somewhere in the plugin there's a StackOverflowException. I'm gonna try to debug it today and maybe fix it.

**Comment by CaptainAmpersand** [comment]
Christ I was expecting you to expect in like a week. If you can get that fixed, that'd be awesome
