### ISSUE TITLE
[Bug] CitizensBooks still won't work at all

### ISSUE THREAD

**Issue by CaptainAmpersand** [NicoNekoDev/AstralBooks#14]
### Information
Server Version: CraftBukkit version git-Spigot-f823ac5-5cffeca (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT) (Latest version 9/24/2018 12:09 AM PST)
Citizens: Citizens version 2.0.24-SNAPSHOT (build 1570) (Updated to most recent build yesterday)
Actual plugin: CitizensBooks version 2.4.5

Full output of `/npcbook about`:
Literally won't work. Can't upload.

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/CaptainAmpersand/3ee1aede63cba64b0609ae98e5d29544

CitizensBooks config (upload `plugins/CitizensBooks/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/CaptainAmpersand/989a865966cc0f12624deb00688887db

### Details

Describe your issue here.
As you can see from the log, no matter what, it won't load, or anything. I can't use this plugin.
It used to work, but now, I get nothing. I deleted the config, I've been trying to use it again. For now, I have citizens that are just... Ugly :(

**Comment by NicoNekoDev** [comment]
May I ask what java version do you use?

**Comment by CaptainAmpersand** [comment]
Unfortunately I don't have a straightforward answer. Here's what Javac and java's versions are on my ubuntu machine:
javac 1.8.0_181

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

Edit: Which means.. After a quick google search (lol), Java 8
