### ISSUE TITLE
[Feature] Signs & books

### ISSUE THREAD

**Issue by NicoNekoDev** [NicoNekoDev/AstralBooks#23]
### Details
Clickable signs:
- clicking on a specific sign will open a book
- the sign format can be customized

**Comment by PikaMug** [comment]
Would also like to see this for ItemFrame and Lectern (where the latter will always open to page 1 instead of last viewed).

**Comment by NicoNekoDev** [comment]
This is added. I've used PersistentDataContainer for blocks and entities and it's working nicely.
Though the release is going to be a bit delayed because I'm also working on a big rewrite for the settings, locale and storage.
