### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by zaccieslak** [NicoNekoDev/AstralBooks#31]
Hey there, firstly thank you for creating this plugin!

I am using the Quests plugin to create quests that have 10+ stages. I've tried to find/figure out a command that will open a new book when a stage starts. 

I'm wondering if there is a command that can be ran to open a book that is saved by the /npc filter set command. If there could be a /npc filter openbook "name of book", that would be awesome! Thanks in advance.

**Comment by NicoNekoDev** [comment]
Using **/npcbook filter set [cirteria name]** you can set a book to "filters".
Using **/npcbook setcmd [command you want players to type so they open the book] [criteria name]** you can set you're own custom command that opens that book you set in the "filter".
Next you just want to do: **/[command you want players to type so they open the book]**
I'm sorry that this wasn't included in any wiki or something.

**Comment by zaccieslak** [comment]
This doesn't work homie ._. 

I did 

/npcbook filter set Book1
/npcbook setcmd OpenBook1 Book1
/OpenBook1

I'm getting "This filter doesn"t have a book!" after I try to do the command. I've tried reloading the plugin and restarting the server and still doesn't work. It'd be awesome if it did though!

**Comment by zaccieslak** [comment]
![image](https://user-images.githubusercontent.com/51010650/69193973-9e71b380-0aed-11ea-817a-78bf5a81d4e7.png)

**Comment by NicoNekoDev** [comment]
That means that it's a bug! What version of spigot does your server run? Is there an error on the console?

**Comment by zaccieslak** [comment]
No error on the console and it's 1.14.4 !

**Comment by NicoNekoDev** [comment]
Ok, I need to test it first and then fix it. Also can you tell me the exact spigot/paper version? Just copy-paste what the command **/version** outputs.

**Comment by zaccieslak** [comment]
This server is running Paper version git-Paper-221 (MC:1.14.4) (Implementing API Version 1.14.4-R0.1-SNAPSHOT)

Alright thanks so much!!

**Comment by NicoNekoDev** [comment]
There was an inconsistency with the config that I accidentaly made. In spigot this was not a problem, but on paper. Now its fixed. I'm gonna push this update later this day on spigot.
