### ISSUE TITLE
Quests with commands [Bug]

### ISSUE THREAD

**Issue by zaccieslak** [NicoNekoDev/AstralBooks#33]
Version: 2.5.3 

So the commands work now with Paper, but executing commands through quest actions/events aren't working. Are you familiar with the Quests?

**Comment by NicoNekoDev** [comment]
Yes. Can you tell me exactly what you're trying/wanting to do?

**Comment by zaccieslak** [comment]
So I have a quest called "Leaving the Nest"

I have 10 stages in the quest, so I've made 10 books.

LeavingTheNestStage1
LeavingTheNestStage2
LeavingTheNestStage3 
And so on. I've made all the npcbook commands, for all of these books and they all work.

I've made Quest Actions that have the command that is associated with the npcbook, but I guess that the command isn't being recognized.

**Comment by zaccieslak** [comment]
![image](https://user-images.githubusercontent.com/51010650/69449557-d0b72700-0d20-11ea-86ab-273fab0920d1.png)

So here you can see the command to execute is "LeavingTheNestStage2"

**Comment by zaccieslak** [comment]
![image](https://user-images.githubusercontent.com/51010650/69449645-fb08e480-0d20-11ea-8549-7b862768c563.png)
When I type it out, it works. But when I try to execute the command through Quest Actions, it doesn't recognize (I'm guessing) that it is a command.

**Comment by zaccieslak** [comment]
![UnknownCommand](https://user-images.githubusercontent.com/51010650/69449989-bc275e80-0d21-11ea-862a-085be74940db.PNG)


yeah, I'm guessing that consoles can't recognize the commands that are set with npcbooks, which means that there's no way to set up books to open with stages then where they auto-open

**Comment by NicoNekoDev** [comment]
OH, well... you trying to force the console to open a book for a player, right?

**Comment by zaccieslak** [comment]
I mean, I'm just using the Quest Actions to execute a command (the command to open the book). 

So when a player finishes a stage in a Quest, a book opens

**Comment by NicoNekoDev** [comment]
So I pushed a quick fix for you, but i'm not gonna push it to spigot yet, because there was some bugs with the updater. You can download the jar from here: http://repo.pikacraft.ro/ro/nicuch/CitizensBooks/2.5.3/CitizensBooks-2.5.3.jar

It adds the command /npcbook forceopen [filter-name] [player-name] which forces a book (from the filter) to open for the given player.

**Comment by zaccieslak** [comment]
ok thanks!! Hopefully the placeholder works, I'll try it out now!

Also, do you know if I'll have to replace every book now?

**Comment by zaccieslak** [comment]
BEAUTIFUL! It works!:) You're freaking awesome.
