### ISSUE TITLE
I'm so sorry ;_; [Bug]

### ISSUE THREAD

**Issue by zaccieslak** [NicoNekoDev/AstralBooks#34]
So books aren't opening with the initial stage of a quest - whether it's the "Initial Action" or "Stage 1" - I'm setting the "/npcbook forceopen "filter name" <player>" command to Quest Actions, and it works when they start a new stage, but for some reason on the initial or Stage 1, they automatically close. I can see for a split second that they open, but then they get closed right away. Is there a way to make it so that npcbooks stay open when accepting a quest?

**Comment by NicoNekoDev** [comment]
Try this version instead:
http://repo.pikacraft.ro/ro/nicuch/CitizensBooks/2.5.4/CitizensBooks-2.5.4.jar
Be aware that its gonna generate a new config, and you have to copy-paste everything from the old config. This is the latest version I've worked today, and contains bug-fixes. I'm hopping it's fixing your bug too. I've had to test everything now for what happened lately. ;-;

**Comment by zaccieslak** [comment]
okay you rock!!

**Comment by zaccieslak** [comment]
Well, the initial stage and Stage 1 book openings don't work with the update - On Paper, 1.14.4 - 

They auto-close for some reason on the first stage of a Quest.

**Comment by NicoNekoDev** [comment]
Can you send a video/gif with this happening? Also I need one that does not have the book set.
Might be Quest fault here.

**Comment by zaccieslak** [comment]
actually, this update caused NPC's to be unable to "/npcbook forceopen "filter name" "player".

It was working in the 2.5.3 you sent, but 2.5.4 doesn't allow books to be opened anymore through stages

**Comment by NicoNekoDev** [comment]
Ok, in the actions.yml in quests, you can have "open-book: [filter name]"
Example:
```  yaml
GiveRod:
    message: "<green>Here you go!"
    items:
      - name-fishing_rod:amount-1
    open-book: "hello_world"
```
This will open the filter book given. I guess this is what you wanted from the start. Quests already had support for my plugin, but I forgot how it worked.

**Comment by zaccieslak** [comment]
oh forreal?? dude that's awesome

**Comment by zaccieslak** [comment]
so I just need to access the actions.yml - not make an action that performs the /npcbook forceopen "filter" "player"

**Comment by NicoNekoDev** [comment]
exactly. well the command it's still good for the plugins that do not have support for CitizensBooks.

**Comment by NicoNekoDev** [comment]
Well if its all fixed, you can close the issue.😁 If not, leave a replay. Tomorrow mornin' i'm gonna release the latest version, fully unbugged I hope. xD

**Comment by zaccieslak** [comment]
Does it need to have quotations around it? I've tried with and without quotations and still doesn't work.

^ Edit: It works - but just not on the initial stage/stage 1 again

**Comment by NicoNekoDev** [comment]
Can you give me the config.yml and actions.yml from quests so I can test them?

**Comment by zaccieslak** [comment]
If you want I'll give you OP on my server - It's still being developed and will be for a couple more months, or I can just shoot you the .yml's

**Comment by NicoNekoDev** [comment]
Send them via discord: nicuch.neko#4012

**Comment by NicoNekoDev** [comment]
Old, probably fixed
