### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by pigvader** [NicoNekoDev/AstralBooks#35]
### Information
Full output of `/npcbook about`:
Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
CitizensBooks config (upload `plugins/CitizensBooks/config.yml` to [Gist](https://gist.github.com/)): 

### Details
hey,

how can i make a Book?
respectively how can i put the Book from the "book Editor" in your PLugin?

On your spigot page it is not explained.

**Comment by NicoNekoDev** [comment]
In the editor you click "generate the command", you copy and paste the command (based on your version) and *boom* you have the book in your hand or inventory (if the command do not work, try replacing "give' with "minecraft:give").

Now to put the book in the plugin depends on what you need it for.
First put the book in your main hand.

If you want to work with Quests, type `/npcbook filter set <name>` to create a filter. In Quests you have to set in the stage (i don't remember were exactly) `open-book: <the name of the filter>`
With NPCs from Citizens you have to select a NPC first, then type `/npcbook set`
For custom commands type `/npcbook filter set <name>` to create a filter and type `/npcbook setcmd <the command in one word> <the filter name> [a.custom.permission.if.you.want]`
