### ISSUE TITLE
[Bug] JitPack build failure

### ISSUE THREAD

**Issue by PikaMug** [NicoNekoDev/AstralBooks#37]
### Information
Not applicable.

### Details
Unable to compile CitizensBooks as of your latest commit 6727506eff05114c3c248f4f740ecde1fdd71076. This is evidenced by https://jitpack.io/com/github/nicuch/CitizensBooks/master-6727506eff-1/build.log

I don't see anything wrong with the commit, so my first impression is that something's gone bad with one of the dependencies.

**Comment by NicoNekoDev** [comment]
Looks like jitpack timed out (obviously it says that at the end), probably one of repos was down when I pushed the commit.
I just pushed https://github.com/nicuch/CitizensBooks/commit/e6b7f1965cf89f5252d649ebb256453890b4756a with no big changes to repos, and now jitpack compiled it correctly.
https://jitpack.io/com/github/nicuch/CitizensBooks/master-e6b7f1965c-1/build.log
