### ISSUE TITLE
[Bug] Some books just disappear from the NPC since update 1.17.1 [version 2.6.6]

### ISSUE THREAD

**Issue by Curiousnoes** [NicoNekoDev/AstralBooks#38]
When I place a book with /npcbook set, it works fine. 
But within a few minutes the books disappears and you are unable to click and receive the book from the NPC.
So when you click, nothing happends.

The weird part is that some books keep working and some books don't.

I created new NPC's and new books but both don't fix the problem.
This issue did not present itself on 1.16.4. It started when I upgraded to 1.17.1.
So I upgraded to NPCbooks 2.6.6 and the issue was still persists.

Can you please fix the issue.

**Comment by NicoNekoDev** [comment]
Are the books still present in the config.yml?
Books for the NPCs are saved there.
First, check if the books are still there, and if they are, check if the NPC ids matches the book ids.

**Comment by Curiousnoes** [comment]
So i did the following.
First i checked the config file and when i look for the ID this shows up in the config:
  '6':
    right_side:
      ==: org.bukkit.inventory.ItemStack
      v: 2730
      type: AIR
      amount: 0

Then i placed the book again, the book pops up when i click on it and i see in the config:
'6':
    right_side:
      ==: org.bukkit.inventory.ItemStack
      v: 2730
      type: WRITTEN_BOOK
      meta:
        ==: ItemMeta
        meta-type: BOOK_SIGNED
        title: Ingeborg Heden
        author: FOTF
        pages:
        - '{"text":"Hoi! Ik ben de officemanager van Firm of the Future. \n\nIk zorg
          ervoor dat alles in en om dit kantoor tot in de puntjes geregeld is. \n\nOh,
          en Mila is mijn hond. Veel plezier in ons kantoor!"}'
        resolved: true

Few minutes later, the book is gone when i click on the NPC again, but the config file still says:
  '6':
    right_side:
      ==: org.bukkit.inventory.ItemStack
      v: 2730
      type: WRITTEN_BOOK
      meta:
        ==: ItemMeta
        meta-type: BOOK_SIGNED
        title: Ingeborg Heden
        author: FOTF
        pages:
        - '{"text":"Hoi! Ik ben de officemanager van Firm of the Future. \n\nIk zorg
          ervoor dat alles in en om dit kantoor tot in de puntjes geregeld is. \n\nOh,
          en Mila is mijn hond. Veel plezier in ons kantoor!"}'
        resolved: true


Now i restart the server. And the config is:
  '6':
    right_side:
      ==: org.bukkit.inventory.ItemStack
      v: 2730
      type: AIR
      amount: 0



________________________________
Van: Drăghiciu Nicolae ***@***.***>
Verzonden: woensdag 1 september 2021 17:33
Aan: NicoNekoDev/CitizensBooks ***@***.***>
CC: Curiousnoes ***@***.***>; Author ***@***.***>
Onderwerp: Re: [NicoNekoDev/CitizensBooks] [Bug] Some books just disappear from the NPC since update 1.17.1 [version 2.6.6] (#38)


Are the books still present in the config.yml?
Books for the NPCs are saved there.
First, check if the books are still there, and if they are, check if the NPC ids matches the book ids.

**Comment by NicoNekoDev** [comment]
I can't replicate this at all. Not sure how you end up with `type: AIR` in the first place, as there is a check for [Material.WRITTEN_BOOK](https://github.com/NicoNekoDev/CitizensBooks/blob/main/citizensbooks/src/main/java/ro/nicuch/citizensbooks/CitizensBooksCommand.java#L553).
Can you provide your server version and a plugin list (or at least the plugins that hook into Citizens)?

**Comment by Curiousnoes** [comment]
It's a real strange issue. The problem started when i upgraded the server from 1.16.4 to 1.17.1.

The server version is Paper Spigot 1.17.1 179

Full list of plugins i use with the server:
BKCommonLib-1.17.1-v2-1111.jar
BannerMaker.jar
Citizens.jar
CitizensBooks-2.6.6.jar
Clearlag.jar
ColoredSigns-4.1.0.jar
CoreProtect-19.3.jar
Denizen-1.2.1-b1744-REL.jar
Dynmap-3.2-beta-2-spigot.jar
EssentialsX-2.19.0.jar
EssentialsXChat-2.19.0.jar
EssentialsXProtect-2.19.0.jar
EssentialsXSpawn-2.18.2.0.jar
EssentialsXSpawn-2.19.0.jar
GroupManager.jar
HolographicDisplays.jar
MacroBukkit.jar
MotionCapture.jar
Multiverse-Core-4.2.2.jar
Multiverse-NetherPortals-4.2.1.jar
Multiverse-Portals-4.2.0.jar
MyWorlds-1.16.4-v1.jar
PlayerNameColors-1.0.1.jar
PsudoCommands.jar
SkinsRestorer.jar
TCCoasters-1.17.1-v1-211.jar
TrainCarts-1.17.1-v1-941.jar
Vault.jar
Vehicles(12.3).jar
WorldBorder.jar
worldedit-bukkit-7.2.6-beta-02.jar
worldguard-bukkit-7.0.6-beta1-dist.jar

________________________________
Van: Drăghiciu Nicolae ***@***.***>
Verzonden: donderdag 2 september 2021 12:28
Aan: NicoNekoDev/CitizensBooks ***@***.***>
CC: Curiousnoes ***@***.***>; Author ***@***.***>
Onderwerp: Re: [NicoNekoDev/CitizensBooks] [Bug] Some books just disappear from the NPC since update 1.17.1 [version 2.6.6] (#38)


I can't replicate this at all. Not sure how you end up with type: AIR in the first place, as there is a check for Material.WRITTEN_BOOK<https://github.com/NicoNekoDev/CitizensBooks/blob/main/citizensbooks/src/main/java/ro/nicuch/citizensbooks/CitizensBooksCommand.java#L553>.
Can you provide your server version and a plugin list (or at least the plugins that hook into Citizens)?

**Comment by NicoNekoDev** [comment]
For now I'll recommend you to update to the latest version of paper and check if it still happens. Not sure if this is related to changing the way books were stored before (as serialized string) to spigot way to store them (as serialized map).

**Comment by NicoNekoDev** [comment]
Update: this bug will not be fixed because:
1) can't replicate in that version
2) in the next version, books will be saved in a json file or in a database and will not use Spigot API for item serialization
