### ISSUE TITLE
Maven repository is down

### ISSUE THREAD

**Issue by PikaMug** [NicoNekoDev/AstralBooks#42]
It seems that https://repo.pikacraft.ro/ is not accessible.

Can't use Jitpack instead because of the SimpleTuples dependency.

**Comment by NicoNekoDev** [comment]
Hey! Please don't update the version yet, I'm working on a big refactoring/internal changes and API breakage atm.
I will fix that when the update is ready.

**Comment by NicoNekoDev** [comment]
No money for a repo + too hard for me to maintain only for a single plugin.
Will put SimpleTuples dependency on Jitpack too after I will do a little bit more work on that library. There's some rewrites to do there too sadly, to have MutableTuples, cuz for now I just create new objects each time I need to modify one value...
