### ISSUE TITLE
New Pages

### ISSUE THREAD

**Issue by MMorozofff** [NicoNekoDev/AstralBooks#43]
How to add new pages in filter? I have used various JSON validators but the plugin can't find the filter after that due to an error.

**Comment by NicoNekoDev** [comment]
You use `/npcbook filter getbook <filter>` to get the book as a written book then `/npcbook openbook` to open the book and edit it.
Please note that books have a limitation of 50 pages iirc.
You can try and send the error and the JSON of that filter so I can take a look at it if you want to.

**Comment by MMorozofff** [comment]
Ok, i understood. Thanks you!
