### ISSUE TITLE
[Bug] Stack errors involving WorldEdit

### ISSUE THREAD

**Issue by pkhodadi** [NicoNekoDev/AstralBooks#44]
### Information
Full output of `/abook about`: 
![2023-04-23_02 31 14](https://user-images.githubusercontent.com/34145971/233831649-44dcfede-1b19-482c-b3a0-9667604e5f58.png)
Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): 
https://gist.github.com/pkhodadi/2be95c7bb2a7ebdbca1c83918a2d2d18#:~:text=%5B09%3A28%3A49,Thread.java%3A833)%20~%5B%3F%3A%3F%5D
AstralBooks config (upload `plugins/AstralBooks/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/pkhodadi/6c0be1ab38a3ae41ec2b1f6aa3a263c9

### Details
Using commands with FastAsyncWorldEdit sends stack errors.

**Comment by NicoNekoDev** [comment]
Thank you for your report. It's gonna be fixed in the next release.
