### ISSUE TITLE
Books filles with raw command data

### ISSUE THREAD

**Issue by VirgilGunder** [NicoNekoDev/AstralBooks#49]
### Information
Full output of `/abook about`:
+----------------------------------+
<+ AstralBooks +>
Version: 3.0.9
Auhtor: NicoNekoDev
+----------------------------------+

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/VirgilGunder/32507e30ecfc61f522b30af79e34fae6

AstralBooks config (upload `plugins/AstralBooks/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/VirgilGunder/1bc3e8b92d51dafaa3689d7b630fd9b6

### Details
Books look like this:
<img width="346" alt="image" src="https://github.com/NicoNekoDev/AstralBooks/assets/69819507/6b7ea181-8f86-45ee-b8b4-56a59723c3ef">

When theyre supposed to be this with commands in the text:
<img width="305" alt="image" src="https://github.com/NicoNekoDev/AstralBooks/assets/69819507/e083d470-7f3b-4ba4-b543-a29c7ed14aba">

**Comment by NicoNekoDev** [comment]
Can you tell me how to reproduce this?

**Comment by VirgilGunder** [comment]
> Can you tell me how to reproduce this?

Did nothing but the command `/astralbooks:npc set left`, whilst holding a book created from the minecraft-book-editor, that you link on the spigot page.

This is said book, but all astralbooks on my server act the same:

/give @p written_book{pages:['["",{"text":" \\u2726","color":"dark_green"},{"text":"Sandkasse-Events","underlined":true,"color":"dark_green"},{"text":"\\u2726","color":"dark_green"},{"text":"\\n","color":"reset"},{"text":"  (Klik for at joine)","color":"gray"},{"text":"\\n\\n","color":"reset"},{"text":" ","clickEvent":{"action":"run_command","value":"/ip join"}},{"text":"Mandag & tirsdag","italic":true,"color":"dark_gray","clickEvent":{"action":"run_command","value":"/ip join"}},{"text":"\\n       Parkour","color":"dark_gray","clickEvent":{"action":"run_command","value":"/ip join"}},{"text":"\\n\\n","color":"dark_gray"},{"text":"       Onsdag","italic":true,"color":"dark_gray"},{"text":"\\n    Kommer senere\\n\\n","color":"dark_gray"},{"text":"  Torsdag & fredag","italic":true,"color":"dark_gray","clickEvent":{"action":"run_command","value":"/ma join"}},{"text":"\\n      MobArena","color":"dark_gray","clickEvent":{"action":"run_command","value":"/ma join"}}]','["",{"text":"/rige - Claim hovedmenuen","color":"gray","clickEvent":{"action":"run_command","value":"/rige"}},{"text":"\\n\\n","color":"reset"},{"text":"/rtp - teleporterer dig til et tilfældigt sted i vildmarken","color":"gray","clickEvent":{"action":"run_command","value":"/rtp"}},{"text":" (Du kan også bruge det svævende skilt i spawn)","italic":true,"color":"gray"}]'],title:EventErik,author:Sandkassen}

**Comment by NicoNekoDev** [comment]
Is the book generated correctly from that command?
Looks like the book generator I linked is outdated. Try this: https://www.gamergeeks.net/apps/minecraft/give-command-generator/written-books

**Comment by VirgilGunder** [comment]
Oh shit I didn't even check, it isn't generated correctly, sorry and never mind :D
